//! SQLite-backed metadata store. Everything live (metrics, container state)
//! stays in memory; the store keeps only what must survive a restart:
//! project registrations/links and the cached GitHub builds/versions.
//! `server_id` exists from day one so multi-server can arrive without a
//! schema migration.

use rusqlite::{params, Connection};
use serde::Serialize;
use std::path::Path;
use std::sync::Mutex;

pub struct Store {
    conn: Mutex<Connection>,
}

#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct Project {
    pub id: i64,
    pub server_id: String,
    pub slug: String,
    pub name: String,
    pub source: String, // "discovered" | "registered"
    pub compose_project: Option<String>,
    pub repo_owner: Option<String>,
    pub repo_name: Option<String>,
    pub domain: Option<String>,
    pub tech: Option<String>,
    /// Wizard lifecycle: NULL for plain projects; 'provisioning' | 'deploying'
    /// while the first deploy is in flight.
    pub status: Option<String>,
    pub auto_domain: Option<String>,
    pub custom_domain: Option<String>,
    pub port: Option<i64>,
    pub created_at: i64,
}

/// A project's database: one Postgres container per project, or a SQLite
/// file discovered inside the project's volumes.
#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct Database {
    pub kind: String, // "postgres" | "sqlite"
    pub container: Option<String>,
    pub db_name: Option<String>,
    pub username: Option<String>,
    #[serde(skip)]
    pub password: Option<String>,
    /// SQLite only: volume/bind source and the file path inside it.
    pub volume: Option<String>,
    pub file_path: Option<String>,
    /// SQLite only: false when the file lives in the container layer and
    /// every deploy wipes it.
    pub persisted: bool,
    pub created_at: i64,
}

#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct LogLine {
    pub ts: i64,
    pub container: String,
    pub stream: String,
    pub line: String,
}

#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct Issue {
    pub id: i64,
    pub fingerprint: String,
    pub title: String,
    pub source: String,
    /// First stack frame's file:line, when the error carried a stack.
    pub culprit: Option<String>,
    pub first_seen: i64,
    pub last_seen: i64,
    pub count: i64,
    /// "open" | "resolved" | "ignored"
    pub state: String,
}

/// One persisted metrics point (5-minute aggregate). `scope` is "server"
/// or "project:<slug>"; the 7-day window is served from these rows, so the
/// history survives webo's own deploys.
#[derive(Clone, Copy, Debug, Serialize, PartialEq)]
pub struct StoredSample {
    pub ts: i64,
    pub cpu_pct: f64,
    pub mem_bytes: i64,
    pub disk_bps: i64,
    pub net_rx_bps: i64,
    pub net_tx_bps: i64,
}

#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct IssueEvent {
    pub ts: i64,
    pub origin: String,
    pub message: String,
}

#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct EnvVar {
    pub key: String,
    pub value: String,
    /// Managed values (DATABASE_URL) are generated by webo and never edited
    /// by hand.
    pub managed: bool,
}

#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct SavedQuery {
    pub name: String,
    pub sql: String,
    pub updated_at: i64,
    pub last_run_at: Option<i64>,
}

#[derive(Clone, Debug, Serialize)]
pub struct Build {
    pub run_id: i64,
    pub workflow: String,
    pub status: String,
    pub conclusion: Option<String>,
    pub commit_sha: String,
    pub commit_msg: String,
    pub branch: String,
    pub duration_secs: i64,
    pub created_at: i64,
}

#[derive(Clone, Debug, Serialize)]
pub struct Version {
    pub tag: String,
    pub current: bool,
    pub size_bytes: Option<i64>,
    pub created_at: i64,
}

const SCHEMA: &str = "
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY,
    server_id TEXT NOT NULL DEFAULT 'local',
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('discovered', 'registered')),
    compose_project TEXT,
    repo_owner TEXT,
    repo_name TEXT,
    domain TEXT,
    tech TEXT,
    status TEXT,
    auto_domain TEXT,
    custom_domain TEXT,
    port INTEGER,
    created_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS builds (
    id INTEGER PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    run_id INTEGER NOT NULL,
    workflow TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL,
    conclusion TEXT,
    commit_sha TEXT NOT NULL,
    commit_msg TEXT NOT NULL,
    branch TEXT NOT NULL,
    duration_secs INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    UNIQUE (project_id, run_id)
);
CREATE INDEX IF NOT EXISTS idx_builds_project ON builds (project_id, created_at DESC);
CREATE TABLE IF NOT EXISTS versions (
    id INTEGER PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    tag TEXT NOT NULL,
    current INTEGER NOT NULL DEFAULT 0,
    size_bytes INTEGER,
    created_at INTEGER NOT NULL,
    UNIQUE (project_id, tag)
);
CREATE INDEX IF NOT EXISTS idx_versions_project ON versions (project_id, created_at DESC);
CREATE TABLE IF NOT EXISTS databases (
    project_id INTEGER PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('postgres', 'sqlite')),
    container TEXT,
    db_name TEXT,
    username TEXT,
    password TEXT,
    volume TEXT,
    file_path TEXT,
    persisted INTEGER NOT NULL DEFAULT 1,
    created_at INTEGER NOT NULL
);
-- full-text log index: survives the container being recreated on deploy
CREATE VIRTUAL TABLE IF NOT EXISTS logs USING fts5(
    line,
    project_id UNINDEXED,
    container UNINDEXED,
    stream UNINDEXED,
    ts UNINDEXED
);
CREATE TABLE IF NOT EXISTS issues (
    id INTEGER PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    fingerprint TEXT NOT NULL,
    title TEXT NOT NULL,
    source TEXT NOT NULL,
    first_seen INTEGER NOT NULL,
    last_seen INTEGER NOT NULL,
    count INTEGER NOT NULL DEFAULT 0,
    resolved INTEGER NOT NULL DEFAULT 0,
    state TEXT NOT NULL DEFAULT 'open',
    culprit TEXT,
    UNIQUE (project_id, fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_issues_project ON issues (project_id, last_seen DESC);
CREATE TABLE IF NOT EXISTS error_events (
    id INTEGER PRIMARY KEY,
    issue_id INTEGER NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    ts INTEGER NOT NULL,
    origin TEXT NOT NULL,
    message TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_issue ON error_events (issue_id, ts DESC);
CREATE TABLE IF NOT EXISTS env_vars (
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    managed INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (project_id, key)
);
CREATE TABLE IF NOT EXISTS saved_queries (
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sql TEXT NOT NULL,
    updated_at INTEGER NOT NULL,
    last_run_at INTEGER,
    PRIMARY KEY (project_id, name)
);
-- 5-minute metric aggregates: the 7-day charts read from here
CREATE TABLE IF NOT EXISTS samples (
    scope TEXT NOT NULL,
    ts INTEGER NOT NULL,
    cpu_pct REAL NOT NULL DEFAULT 0,
    mem_bytes INTEGER NOT NULL DEFAULT 0,
    disk_bps INTEGER NOT NULL DEFAULT 0,
    net_rx_bps INTEGER NOT NULL DEFAULT 0,
    net_tx_bps INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (scope, ts)
);
CREATE INDEX IF NOT EXISTS idx_samples_scope ON samples (scope, ts DESC);
";

/// Additive migrations for databases created by older versions —
/// CREATE TABLE IF NOT EXISTS never alters an existing table.
fn migrate(conn: &Connection) {
    let _ = conn.execute("ALTER TABLE builds ADD COLUMN workflow TEXT NOT NULL DEFAULT ''", []);
    let _ = conn.execute("ALTER TABLE projects ADD COLUMN tech TEXT", []);
    let _ = conn.execute("ALTER TABLE projects ADD COLUMN status TEXT", []);
    let _ = conn.execute("ALTER TABLE projects ADD COLUMN auto_domain TEXT", []);
    let _ = conn.execute("ALTER TABLE projects ADD COLUMN custom_domain TEXT", []);
    let _ = conn.execute("ALTER TABLE projects ADD COLUMN port INTEGER", []);
    let _ = conn.execute("ALTER TABLE issues ADD COLUMN state TEXT NOT NULL DEFAULT 'open'", []);
    let _ = conn.execute("ALTER TABLE issues ADD COLUMN culprit TEXT", []);
    // databases from before the state column carried resolution as a flag
    let _ = conn.execute("UPDATE issues SET state = 'resolved' WHERE resolved = 1 AND state = 'open'", []);
}

impl Store {
    pub fn open(path: &Path) -> rusqlite::Result<Self> {
        let conn = Connection::open(path)?;
        conn.execute_batch("PRAGMA journal_mode = WAL; PRAGMA foreign_keys = ON;")?;
        conn.execute_batch(SCHEMA)?;
        migrate(&conn);
        Ok(Self { conn: Mutex::new(conn) })
    }

    pub fn open_in_memory() -> rusqlite::Result<Self> {
        let conn = Connection::open_in_memory()?;
        conn.execute_batch("PRAGMA foreign_keys = ON;")?;
        conn.execute_batch(SCHEMA)?;
        migrate(&conn);
        Ok(Self { conn: Mutex::new(conn) })
    }

    /// Discovery upsert: creates the project on first sight, and fills in
    /// repo/domain when discovery learns them — but NEVER overwrites values
    /// that already exist (a user-made link beats inference).
    pub fn upsert_discovered(
        &self,
        slug: &str,
        compose_project: &str,
        repo: Option<(&str, &str)>,
        domain: Option<&str>,
        now: i64,
    ) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO projects (slug, name, source, compose_project, repo_owner, repo_name, domain, created_at)
             VALUES (?1, ?1, 'discovered', ?2, ?3, ?4, ?5, ?6)
             ON CONFLICT (slug) DO UPDATE SET
                compose_project = excluded.compose_project,
                repo_owner = COALESCE(projects.repo_owner, excluded.repo_owner),
                repo_name = COALESCE(projects.repo_name, excluded.repo_name),
                domain = COALESCE(projects.domain, excluded.domain)",
            params![slug, compose_project, repo.map(|r| r.0), repo.map(|r| r.1), domain, now],
        )?;
        Ok(())
    }

    pub fn projects(&self) -> rusqlite::Result<Vec<Project>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT id, server_id, slug, name, source, compose_project, repo_owner, repo_name, domain, tech, status,
                    auto_domain, custom_domain, port, created_at
             FROM projects ORDER BY name",
        )?;
        let rows = stmt.query_map([], |r| {
            Ok(Project {
                id: r.get(0)?,
                server_id: r.get(1)?,
                slug: r.get(2)?,
                name: r.get(3)?,
                source: r.get(4)?,
                compose_project: r.get(5)?,
                repo_owner: r.get(6)?,
                repo_name: r.get(7)?,
                domain: r.get(8)?,
                tech: r.get(9)?,
                status: r.get(10)?,
                auto_domain: r.get(11)?,
                custom_domain: r.get(12)?,
                port: r.get(13)?,
                created_at: r.get(14)?,
            })
        })?;
        rows.collect()
    }

    /// Wizard entry point: an explicit registration. Unlike discovery, the
    /// repo link is authoritative here (and upgrades a discovered project).
    pub fn register(
        &self,
        slug: &str,
        repo_owner: &str,
        repo_name: &str,
        tech: &str,
        now: i64,
    ) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO projects (slug, name, source, repo_owner, repo_name, tech, status, created_at)
             VALUES (?1, ?1, 'registered', ?2, ?3, ?4, 'provisioning', ?5)
             ON CONFLICT (slug) DO UPDATE SET
                source = 'registered',
                repo_owner = excluded.repo_owner,
                repo_name = excluded.repo_name,
                tech = excluded.tech,
                status = COALESCE(projects.status, 'provisioning')",
            params![slug, repo_owner, repo_name, tech, now],
        )?;
        Ok(())
    }

    /// Removes the project row; builds and versions go with it (CASCADE).
    pub fn delete_project(&self, slug: &str) -> rusqlite::Result<bool> {
        let conn = self.conn.lock().unwrap();
        Ok(conn.execute("DELETE FROM projects WHERE slug = ?1", params![slug])? > 0)
    }

    /// Reserves the auto domain once — it must never change for a project.
    pub fn set_auto_domain_if_empty(&self, slug: &str, domain: &str, port: i64) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "UPDATE projects SET auto_domain = COALESCE(auto_domain, ?1), port = COALESCE(port, ?2)
             WHERE slug = ?3",
            params![domain, port, slug],
        )?;
        Ok(())
    }

    pub fn set_custom_domain(&self, slug: &str, domain: Option<&str>) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute("UPDATE projects SET custom_domain = ?1 WHERE slug = ?2", params![domain, slug])?;
        Ok(())
    }

    /// Every hostname webo manages, for reconciling the tunnel ingress.
    pub fn routes(&self) -> rusqlite::Result<Vec<(String, String)>> {
        let mut out = Vec::new();
        for p in self.projects()? {
            let service = format!(
                "http://{}:{}",
                p.compose_project.clone().unwrap_or_else(|| p.slug.clone()),
                p.port.unwrap_or(3000)
            );
            for host in [p.auto_domain.clone(), p.custom_domain.clone()].into_iter().flatten() {
                out.push((host, service.clone()));
            }
        }
        Ok(out)
    }

    pub fn set_database(&self, project_id: i64, db: &Database) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO databases (project_id, kind, container, db_name, username, password, volume, file_path, persisted, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
             ON CONFLICT (project_id) DO UPDATE SET
                kind = excluded.kind, container = excluded.container, db_name = excluded.db_name,
                username = excluded.username, password = COALESCE(excluded.password, databases.password),
                volume = excluded.volume, file_path = excluded.file_path, persisted = excluded.persisted",
            params![
                project_id, db.kind, db.container, db.db_name, db.username, db.password,
                db.volume, db.file_path, db.persisted as i64, db.created_at
            ],
        )?;
        Ok(())
    }

    pub fn database(&self, project_id: i64) -> rusqlite::Result<Option<Database>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT kind, container, db_name, username, password, volume, file_path, persisted, created_at
             FROM databases WHERE project_id = ?1",
        )?;
        let mut rows = stmt.query_map(params![project_id], |r| {
            Ok(Database {
                kind: r.get(0)?,
                container: r.get(1)?,
                db_name: r.get(2)?,
                username: r.get(3)?,
                password: r.get(4)?,
                volume: r.get(5)?,
                file_path: r.get(6)?,
                persisted: r.get::<_, i64>(7)? != 0,
                created_at: r.get(8)?,
            })
        })?;
        rows.next().transpose()
    }

    pub fn delete_database(&self, project_id: i64) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute("DELETE FROM databases WHERE project_id = ?1", params![project_id])?;
        Ok(())
    }

    /// Appends collected lines. Cheap and batched: the collector calls this
    /// every few seconds with whatever is new.
    pub fn insert_logs(&self, project_id: i64, lines: &[LogLine]) -> rusqlite::Result<usize> {
        if lines.is_empty() {
            return Ok(0);
        }
        let mut conn = self.conn.lock().unwrap();
        let tx = conn.transaction()?;
        for l in lines {
            tx.execute(
                "INSERT INTO logs (line, project_id, container, stream, ts) VALUES (?1, ?2, ?3, ?4, ?5)",
                params![l.line, project_id, l.container, l.stream, l.ts],
            )?;
        }
        tx.commit()?;
        Ok(lines.len())
    }

    /// Newest timestamp stored for a container, so collection resumes where
    /// it stopped instead of re-reading everything.
    pub fn last_log_ts(&self, project_id: i64, container: &str) -> rusqlite::Result<Option<i64>> {
        let conn = self.conn.lock().unwrap();
        conn.query_row(
            "SELECT MAX(CAST(ts AS INTEGER)) FROM logs WHERE project_id = ?1 AND container = ?2",
            params![project_id, container],
            |r| r.get::<_, Option<i64>>(0),
        )
    }

    /// Search: free text (FTS5 when a query is given), optional container and
    /// time window, newest first.
    pub fn search_logs(
        &self,
        project_id: i64,
        query: Option<&str>,
        container: Option<&str>,
        since: Option<i64>,
        limit: usize,
    ) -> rusqlite::Result<Vec<LogLine>> {
        let conn = self.conn.lock().unwrap();
        let mut sql = String::from(
            "SELECT CAST(ts AS INTEGER) AS t, container, stream, line FROM logs WHERE project_id = ?1",
        );
        if query.is_some() {
            sql.push_str(" AND logs MATCH ?2");
        }
        let mut out = Vec::new();
        let filter_container = container.map(|c| c.to_string());
        let since = since.unwrap_or(0);
        sql.push_str(" ORDER BY t DESC LIMIT 5000");
        let mut stmt = conn.prepare(&sql)?;
        let mut push = |rows: rusqlite::MappedRows<'_, _>| -> rusqlite::Result<()> {
            for row in rows {
                let l: LogLine = row?;
                if l.ts < since {
                    continue;
                }
                if filter_container.as_ref().is_some_and(|c| &l.container != c) {
                    continue;
                }
                if out.len() < limit {
                    out.push(l);
                }
            }
            Ok(())
        };
        let map = |r: &rusqlite::Row| {
            Ok(LogLine { ts: r.get(0)?, container: r.get(1)?, stream: r.get(2)?, line: r.get(3)? })
        };
        match query {
            Some(q) => push(stmt.query_map(params![project_id, q], map)?)?,
            None => push(stmt.query_map(params![project_id], map)?)?,
        }
        Ok(out)
    }

    /// Bytes a project's logs occupy, and pruning of the oldest lines above
    /// the cap — a runaway app must never fill the disk.
    pub fn logs_bytes(&self, project_id: i64) -> rusqlite::Result<i64> {
        let conn = self.conn.lock().unwrap();
        conn.query_row(
            "SELECT COALESCE(SUM(LENGTH(line)), 0) FROM logs WHERE project_id = ?1",
            params![project_id],
            |r| r.get(0),
        )
    }

    pub fn prune_logs(&self, project_id: i64, max_bytes: i64) -> rusqlite::Result<usize> {
        if self.logs_bytes(project_id)? <= max_bytes {
            return Ok(0);
        }
        let conn = self.conn.lock().unwrap();
        // drop the oldest tenth and let the next pass check again
        let removed = conn.execute(
            "DELETE FROM logs WHERE rowid IN (
                SELECT rowid FROM logs WHERE project_id = ?1
                ORDER BY CAST(ts AS INTEGER) ASC
                LIMIT MAX(100, (SELECT COUNT(*) / 10 FROM logs WHERE project_id = ?1))
            )",
            params![project_id],
        )?;
        Ok(removed)
    }

    pub fn delete_logs(&self, project_id: i64) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute("DELETE FROM logs WHERE project_id = ?1", params![project_id])?;
        Ok(())
    }

    /// Records one occurrence: creates the issue on first sight, otherwise
    /// bumps its count and last_seen. A resolved issue that happens again
    /// comes back open — it clearly was not fixed.
    #[allow(clippy::too_many_arguments)]
    pub fn record_error(
        &self,
        project_id: i64,
        fingerprint: &str,
        title: &str,
        source: &str,
        origin: &str,
        message: &str,
        ts: i64,
        culprit: Option<&str>,
    ) -> rusqlite::Result<i64> {
        let mut conn = self.conn.lock().unwrap();
        let tx = conn.transaction()?;
        // a resolved issue that happens again reopens (it was not fixed);
        // an IGNORED one stays ignored — that is what ignoring means
        tx.execute(
            "INSERT INTO issues (project_id, fingerprint, title, source, first_seen, last_seen, count, resolved, state, culprit)
             VALUES (?1, ?2, ?3, ?4, ?5, ?5, 1, 0, 'open', ?6)
             ON CONFLICT (project_id, fingerprint) DO UPDATE SET
                last_seen = MAX(issues.last_seen, excluded.last_seen),
                count = issues.count + 1,
                resolved = CASE WHEN issues.state = 'ignored' THEN issues.resolved ELSE 0 END,
                state = CASE WHEN issues.state = 'ignored' THEN 'ignored' ELSE 'open' END,
                culprit = COALESCE(issues.culprit, excluded.culprit)",
            params![project_id, fingerprint, title, source, ts, culprit],
        )?;
        let id: i64 = tx.query_row(
            "SELECT id FROM issues WHERE project_id = ?1 AND fingerprint = ?2",
            params![project_id, fingerprint],
            |r| r.get(0),
        )?;
        tx.execute(
            "INSERT INTO error_events (issue_id, ts, origin, message) VALUES (?1, ?2, ?3, ?4)",
            params![id, ts, origin, message],
        )?;
        // keep only the most recent occurrences of each issue
        tx.execute(
            "DELETE FROM error_events WHERE issue_id = ?1 AND id NOT IN (
                SELECT id FROM error_events WHERE issue_id = ?1 ORDER BY ts DESC LIMIT 50
            )",
            params![id],
        )?;
        tx.commit()?;
        Ok(id)
    }

    /// Issues filtered by state; `None` lists everything.
    pub fn issues(&self, project_id: i64, state: Option<&str>) -> rusqlite::Result<Vec<Issue>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT id, fingerprint, title, source, culprit, first_seen, last_seen, count, state
             FROM issues WHERE project_id = ?1 AND (?2 IS NULL OR state = ?2)
             ORDER BY last_seen DESC LIMIT 200",
        )?;
        let rows = stmt.query_map(params![project_id, state], |r| {
            Ok(Issue {
                id: r.get(0)?,
                fingerprint: r.get(1)?,
                title: r.get(2)?,
                source: r.get(3)?,
                culprit: r.get(4)?,
                first_seen: r.get(5)?,
                last_seen: r.get(6)?,
                count: r.get(7)?,
                state: r.get(8)?,
            })
        })?;
        rows.collect()
    }

    /// (open, resolved, ignored) counts for the header chips.
    pub fn issue_counts(&self, project_id: i64) -> rusqlite::Result<(i64, i64, i64)> {
        let conn = self.conn.lock().unwrap();
        conn.query_row(
            "SELECT
                COALESCE(SUM(state = 'open'), 0),
                COALESCE(SUM(state = 'resolved'), 0),
                COALESCE(SUM(state = 'ignored'), 0)
             FROM issues WHERE project_id = ?1",
            params![project_id],
            |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
        )
    }

    /// Bulk state change; returns how many rows changed.
    pub fn set_issue_state(&self, project_id: i64, ids: &[i64], state: &str) -> rusqlite::Result<usize> {
        if !matches!(state, "open" | "resolved" | "ignored") || ids.is_empty() {
            return Ok(0);
        }
        let conn = self.conn.lock().unwrap();
        let mut changed = 0;
        for id in ids {
            changed += conn.execute(
                "UPDATE issues SET state = ?1, resolved = (?1 = 'resolved') WHERE id = ?2 AND project_id = ?3",
                params![state, id, project_id],
            )?;
        }
        Ok(changed)
    }

    /// Deletes issues and their events (CASCADE); returns how many went.
    pub fn delete_issues(&self, project_id: i64, ids: &[i64]) -> rusqlite::Result<usize> {
        let conn = self.conn.lock().unwrap();
        let mut removed = 0;
        for id in ids {
            removed += conn.execute(
                "DELETE FROM issues WHERE id = ?1 AND project_id = ?2",
                params![id, project_id],
            )?;
        }
        Ok(removed)
    }

    /// Timestamps of the stored occurrences, oldest first — the per-issue
    /// sparkline is drawn from these.
    pub fn event_timestamps(&self, issue_id: i64, limit: usize) -> rusqlite::Result<Vec<i64>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT ts FROM error_events WHERE issue_id = ?1 ORDER BY ts DESC LIMIT ?2",
        )?;
        let rows = stmt.query_map(params![issue_id, limit as i64], |r| r.get::<_, i64>(0))?;
        let mut out: Vec<i64> = rows.collect::<Result<_, _>>()?;
        out.reverse();
        Ok(out)
    }

    pub fn open_issue_count(&self, project_id: i64) -> rusqlite::Result<i64> {
        let conn = self.conn.lock().unwrap();
        conn.query_row(
            "SELECT COUNT(*) FROM issues WHERE project_id = ?1 AND state = 'open'",
            params![project_id],
            |r| r.get(0),
        )
    }

    pub fn issue_events(&self, issue_id: i64, limit: usize) -> rusqlite::Result<Vec<IssueEvent>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT ts, origin, message FROM error_events WHERE issue_id = ?1 ORDER BY ts DESC LIMIT ?2",
        )?;
        let rows = stmt.query_map(params![issue_id, limit as i64], |r| {
            Ok(IssueEvent { ts: r.get(0)?, origin: r.get(1)?, message: r.get(2)? })
        })?;
        rows.collect()
    }

    pub fn resolve_issue(&self, project_id: i64, issue_id: i64, resolved: bool) -> rusqlite::Result<bool> {
        Ok(self.set_issue_state(project_id, &[issue_id], if resolved { "resolved" } else { "open" })? > 0)
    }

    // ---------- saved SQL queries ----------

    pub fn save_query(&self, project_id: i64, name: &str, sql: &str, now: i64) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO saved_queries (project_id, name, sql, updated_at)
             VALUES (?1, ?2, ?3, ?4)
             ON CONFLICT (project_id, name) DO UPDATE SET sql = excluded.sql, updated_at = excluded.updated_at",
            params![project_id, name, sql, now],
        )?;
        Ok(())
    }

    pub fn saved_queries(&self, project_id: i64) -> rusqlite::Result<Vec<SavedQuery>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT name, sql, updated_at, last_run_at FROM saved_queries
             WHERE project_id = ?1 ORDER BY COALESCE(last_run_at, updated_at) DESC",
        )?;
        let rows = stmt.query_map(params![project_id], |r| {
            Ok(SavedQuery { name: r.get(0)?, sql: r.get(1)?, updated_at: r.get(2)?, last_run_at: r.get(3)? })
        })?;
        rows.collect()
    }

    pub fn delete_query(&self, project_id: i64, name: &str) -> rusqlite::Result<bool> {
        let conn = self.conn.lock().unwrap();
        Ok(conn.execute(
            "DELETE FROM saved_queries WHERE project_id = ?1 AND name = ?2",
            params![project_id, name],
        )? > 0)
    }

    /// Bumps last_run_at when a saved query is executed, so the sidebar
    /// orders by real use.
    pub fn mark_query_run(&self, project_id: i64, name: &str, now: i64) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "UPDATE saved_queries SET last_run_at = ?1 WHERE project_id = ?2 AND name = ?3",
            params![now, project_id, name],
        )?;
        Ok(())
    }

    // ---------- persisted metric samples (the 7-day window) ----------

    pub fn insert_sample(&self, scope: &str, s: &StoredSample) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO samples (scope, ts, cpu_pct, mem_bytes, disk_bps, net_rx_bps, net_tx_bps)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
             ON CONFLICT (scope, ts) DO UPDATE SET
                cpu_pct = excluded.cpu_pct, mem_bytes = excluded.mem_bytes,
                disk_bps = excluded.disk_bps, net_rx_bps = excluded.net_rx_bps,
                net_tx_bps = excluded.net_tx_bps",
            params![scope, s.ts, s.cpu_pct, s.mem_bytes, s.disk_bps, s.net_rx_bps, s.net_tx_bps],
        )?;
        Ok(())
    }

    pub fn samples(&self, scope: &str, since: i64) -> rusqlite::Result<Vec<StoredSample>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT ts, cpu_pct, mem_bytes, disk_bps, net_rx_bps, net_tx_bps
             FROM samples WHERE scope = ?1 AND ts >= ?2 ORDER BY ts ASC LIMIT 4032",
        )?;
        let rows = stmt.query_map(params![scope, since], |r| {
            Ok(StoredSample {
                ts: r.get(0)?,
                cpu_pct: r.get(1)?,
                mem_bytes: r.get(2)?,
                disk_bps: r.get(3)?,
                net_rx_bps: r.get(4)?,
                net_tx_bps: r.get(5)?,
            })
        })?;
        rows.collect()
    }

    pub fn prune_samples(&self, before: i64) -> rusqlite::Result<usize> {
        let conn = self.conn.lock().unwrap();
        conn.execute("DELETE FROM samples WHERE ts < ?1", params![before])
    }

    /// The ingest key a project's browser snippet carries. Created on demand.
    pub fn ingest_key(&self, project_id: i64) -> rusqlite::Result<String> {
        if let Some(v) = self
            .env_vars(project_id)?
            .into_iter()
            .find(|v| v.key == "__WEBO_INGEST_KEY")
        {
            return Ok(v.value);
        }
        let key = crate::db::generate_password();
        self.set_env(project_id, "__WEBO_INGEST_KEY", &key, true)?;
        Ok(key)
    }

    pub fn project_by_ingest_key(&self, key: &str) -> rusqlite::Result<Option<i64>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT project_id FROM env_vars WHERE key = '__WEBO_INGEST_KEY' AND value = ?1",
        )?;
        let mut rows = stmt.query_map(params![key], |r| r.get::<_, i64>(0))?;
        rows.next().transpose()
    }

    pub fn set_env(&self, project_id: i64, key: &str, value: &str, managed: bool) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO env_vars (project_id, key, value, managed) VALUES (?1, ?2, ?3, ?4)
             ON CONFLICT (project_id, key) DO UPDATE SET value = excluded.value, managed = excluded.managed",
            params![project_id, key, value, managed as i64],
        )?;
        Ok(())
    }

    pub fn env_vars(&self, project_id: i64) -> rusqlite::Result<Vec<EnvVar>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT key, value, managed FROM env_vars WHERE project_id = ?1 ORDER BY managed DESC, key",
        )?;
        let rows = stmt.query_map(params![project_id], |r| {
            Ok(EnvVar { key: r.get(0)?, value: r.get(1)?, managed: r.get::<_, i64>(2)? != 0 })
        })?;
        rows.collect()
    }

    /// Hand-made variables can be deleted; managed ones only go with their
    /// database.
    pub fn delete_env(&self, project_id: i64, key: &str) -> rusqlite::Result<bool> {
        let conn = self.conn.lock().unwrap();
        Ok(conn.execute(
            "DELETE FROM env_vars WHERE project_id = ?1 AND key = ?2 AND managed = 0",
            params![project_id, key],
        )? > 0)
    }

    pub fn set_status(&self, slug: &str, status: Option<&str>) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute("UPDATE projects SET status = ?1 WHERE slug = ?2", params![status, slug])?;
        Ok(())
    }

    /// Fills the detected technology once; a value already present wins
    /// (a template choice beats language inference).
    pub fn set_tech_if_empty(&self, slug: &str, tech: &str) -> rusqlite::Result<()> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "UPDATE projects SET tech = ?1 WHERE slug = ?2 AND tech IS NULL",
            params![tech, slug],
        )?;
        Ok(())
    }

    pub fn project_by_slug(&self, slug: &str) -> rusqlite::Result<Option<Project>> {
        Ok(self.projects()?.into_iter().find(|p| p.slug == slug))
    }

    pub fn replace_builds(&self, project_id: i64, builds: &[Build]) -> rusqlite::Result<()> {
        let mut conn = self.conn.lock().unwrap();
        let tx = conn.transaction()?;
        for b in builds {
            tx.execute(
                "INSERT INTO builds (project_id, run_id, workflow, status, conclusion, commit_sha, commit_msg, branch, duration_secs, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
                 ON CONFLICT (project_id, run_id) DO UPDATE SET
                    workflow = excluded.workflow,
                    status = excluded.status,
                    conclusion = excluded.conclusion,
                    duration_secs = excluded.duration_secs",
                params![
                    project_id, b.run_id, b.workflow, b.status, b.conclusion, b.commit_sha,
                    b.commit_msg, b.branch, b.duration_secs, b.created_at
                ],
            )?;
        }
        tx.commit()
    }

    pub fn builds(&self, project_id: i64, limit: usize) -> rusqlite::Result<Vec<Build>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT run_id, workflow, status, conclusion, commit_sha, commit_msg, branch, duration_secs, created_at
             FROM builds WHERE project_id = ?1 ORDER BY created_at DESC LIMIT ?2",
        )?;
        let rows = stmt.query_map(params![project_id, limit as i64], |r| {
            Ok(Build {
                run_id: r.get(0)?,
                workflow: r.get(1)?,
                status: r.get(2)?,
                conclusion: r.get(3)?,
                commit_sha: r.get(4)?,
                commit_msg: r.get(5)?,
                branch: r.get(6)?,
                duration_secs: r.get(7)?,
                created_at: r.get(8)?,
            })
        })?;
        rows.collect()
    }

    pub fn replace_versions(&self, project_id: i64, versions: &[Version]) -> rusqlite::Result<()> {
        let mut conn = self.conn.lock().unwrap();
        let tx = conn.transaction()?;
        tx.execute("UPDATE versions SET current = 0 WHERE project_id = ?1", params![project_id])?;
        for v in versions {
            tx.execute(
                "INSERT INTO versions (project_id, tag, current, size_bytes, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5)
                 ON CONFLICT (project_id, tag) DO UPDATE SET
                    current = excluded.current,
                    size_bytes = COALESCE(excluded.size_bytes, versions.size_bytes)",
                params![project_id, v.tag, v.current as i64, v.size_bytes, v.created_at],
            )?;
        }
        tx.commit()
    }

    pub fn versions(&self, project_id: i64, limit: usize) -> rusqlite::Result<Vec<Version>> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT tag, current, size_bytes, created_at
             FROM versions WHERE project_id = ?1 ORDER BY created_at DESC LIMIT ?2",
        )?;
        let rows = stmt.query_map(params![project_id, limit as i64], |r| {
            Ok(Version {
                tag: r.get(0)?,
                current: r.get::<_, i64>(1)? != 0,
                size_bytes: r.get(2)?,
                created_at: r.get(3)?,
            })
        })?;
        rows.collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn store() -> Store {
        Store::open_in_memory().unwrap()
    }

    #[test]
    fn discovery_creates_and_updates_without_clobbering() {
        let s = store();
        s.upsert_discovered("codo", "codo", None, None, 100).unwrap();
        let p = s.project_by_slug("codo").unwrap().unwrap();
        assert_eq!(p.source, "discovered");
        assert_eq!(p.repo_owner, None);
        assert_eq!(p.server_id, "local");

        // discovery later learns the repo and domain
        s.upsert_discovered("codo", "codo", Some(("murichristopher", "codo")), Some("codo.example.com"), 200).unwrap();
        let p = s.project_by_slug("codo").unwrap().unwrap();
        assert_eq!(p.repo_owner.as_deref(), Some("murichristopher"));
        assert_eq!(p.domain.as_deref(), Some("codo.example.com"));
        assert_eq!(p.created_at, 100, "created_at keeps the first sighting");

        // inference can NOT overwrite an existing link
        s.upsert_discovered("codo", "codo", Some(("someone", "else")), Some("other.example.com"), 300).unwrap();
        let p = s.project_by_slug("codo").unwrap().unwrap();
        assert_eq!(p.repo_owner.as_deref(), Some("murichristopher"));
        assert_eq!(p.domain.as_deref(), Some("codo.example.com"));
    }

    #[test]
    fn projects_are_sorted_by_name() {
        let s = store();
        s.upsert_discovered("webo", "webo", None, None, 1).unwrap();
        s.upsert_discovered("codo", "codo", None, None, 2).unwrap();
        let names: Vec<String> = s.projects().unwrap().into_iter().map(|p| p.name).collect();
        assert_eq!(names, vec!["codo", "webo"]);
    }

    #[test]
    fn builds_replace_updates_status_and_orders_desc() {
        let s = store();
        s.upsert_discovered("codo", "codo", None, None, 1).unwrap();
        let id = s.project_by_slug("codo").unwrap().unwrap().id;
        let b = |run_id, status: &str, created| Build {
            run_id,
            workflow: "Deploy".into(),
            status: status.into(),
            conclusion: None,
            commit_sha: "abc1234".into(),
            commit_msg: "msg".into(),
            branch: "main".into(),
            duration_secs: 60,
            created_at: created,
        };
        s.replace_builds(id, &[b(1, "in_progress", 10), b(2, "completed", 20)]).unwrap();
        s.replace_builds(id, &[b(1, "completed", 10)]).unwrap();
        let builds = s.builds(id, 10).unwrap();
        assert_eq!(builds.len(), 2);
        assert_eq!(builds[0].run_id, 2, "newest first");
        assert_eq!(builds[1].status, "completed", "run 1 was updated in place");
    }

    #[test]
    fn versions_replace_moves_the_current_flag() {
        let s = store();
        s.upsert_discovered("codo", "codo", None, None, 1).unwrap();
        let id = s.project_by_slug("codo").unwrap().unwrap().id;
        let v = |tag: &str, current, created| Version {
            tag: tag.into(),
            current,
            size_bytes: Some(96_000_000),
            created_at: created,
        };
        s.replace_versions(id, &[v("aaa", true, 10), v("bbb", false, 5)]).unwrap();
        s.replace_versions(id, &[v("ccc", true, 20), v("aaa", false, 10)]).unwrap();
        let versions = s.versions(id, 10).unwrap();
        assert_eq!(versions[0].tag, "ccc");
        assert!(versions[0].current);
        assert!(!versions.iter().any(|x| x.tag == "aaa" && x.current), "current moved off aaa");
    }

    #[test]
    fn builds_and_versions_isolated_per_project() {
        let s = store();
        s.upsert_discovered("a", "a", None, None, 1).unwrap();
        s.upsert_discovered("b", "b", None, None, 1).unwrap();
        let a = s.project_by_slug("a").unwrap().unwrap().id;
        let b_id = s.project_by_slug("b").unwrap().unwrap().id;
        s.replace_builds(a, &[Build {
            run_id: 1, workflow: "Deploy".into(), status: "completed".into(), conclusion: Some("success".into()),
            commit_sha: "x".into(), commit_msg: "m".into(), branch: "main".into(),
            duration_secs: 1, created_at: 1,
        }]).unwrap();
        assert_eq!(s.builds(a, 10).unwrap().len(), 1);
        assert!(s.builds(b_id, 10).unwrap().is_empty());
    }

    #[test]
    fn register_upgrades_discovered_and_status_lifecycle() {
        let s = store();
        s.upsert_discovered("axofin", "axofin", None, None, 1).unwrap();
        s.register("axofin", "murichristopher", "axofin", "ruby", 2).unwrap();
        let p = s.project_by_slug("axofin").unwrap().unwrap();
        assert_eq!(p.source, "registered");
        assert_eq!(p.repo_owner.as_deref(), Some("murichristopher"));
        assert_eq!(p.tech.as_deref(), Some("ruby"));
        assert_eq!(p.status.as_deref(), Some("provisioning"));

        s.set_status("axofin", Some("deploying")).unwrap();
        assert_eq!(s.project_by_slug("axofin").unwrap().unwrap().status.as_deref(), Some("deploying"));
        s.set_status("axofin", None).unwrap();
        assert_eq!(s.project_by_slug("axofin").unwrap().unwrap().status, None);

        // discovery afterwards must not clobber the registration
        s.upsert_discovered("axofin", "axofin", Some(("other", "repo")), None, 3).unwrap();
        let p = s.project_by_slug("axofin").unwrap().unwrap();
        assert_eq!(p.source, "registered");
        assert_eq!(p.repo_owner.as_deref(), Some("murichristopher"));
    }

    #[test]
    fn errors_group_count_and_reopen() {
        let s = store();
        s.upsert_discovered("app", "app", None, None, 1).unwrap();
        let id = s.project_by_slug("app").unwrap().unwrap().id;

        let issue = s.record_error(id, "fp-a", "connection refused", "server", "app", "ERROR connection refused", 100, Some("lib/db.ts:12")).unwrap();
        s.record_error(id, "fp-a", "connection refused", "server", "app", "ERROR connection refused again", 200, None).unwrap();
        s.record_error(id, "fp-b", "x is not a function", "browser", "https://x/checkout", "TypeError", 150, None).unwrap();

        let issues = s.issues(id, Some("open")).unwrap();
        assert_eq!(issues.len(), 2);
        assert_eq!(issues[0].fingerprint, "fp-a", "most recent first");
        assert_eq!(issues[0].count, 2, "occurrences are counted, not duplicated");
        assert_eq!(issues[0].first_seen, 100);
        assert_eq!(issues[0].last_seen, 200);
        assert_eq!(issues[0].culprit.as_deref(), Some("lib/db.ts:12"), "first culprit sticks");
        assert_eq!(issues[1].source, "browser");
        assert_eq!(s.open_issue_count(id).unwrap(), 2);

        // occurrences are kept per issue, and their timestamps drive the spark
        let events = s.issue_events(issue, 10).unwrap();
        assert_eq!(events.len(), 2);
        assert!(events[0].message.contains("again"), "newest first");
        assert_eq!(s.event_timestamps(issue, 10).unwrap(), vec![100, 200], "oldest first");

        // resolving hides it — until it happens again
        assert!(s.resolve_issue(id, issue, true).unwrap());
        assert_eq!(s.issues(id, Some("open")).unwrap().len(), 1);
        assert_eq!(s.issues(id, None).unwrap().len(), 2, "resolved still listable");
        assert_eq!(s.issue_counts(id).unwrap(), (1, 1, 0));
        assert_eq!(s.open_issue_count(id).unwrap(), 1);
        s.record_error(id, "fp-a", "connection refused", "server", "app", "voltou", 300, None).unwrap();
        assert_eq!(s.open_issue_count(id).unwrap(), 2, "a resolved issue that happens again reopens");

        // the ingest key is stable and finds its project back
        let key = s.ingest_key(id).unwrap();
        assert_eq!(s.ingest_key(id).unwrap(), key, "the key never changes");
        assert_eq!(s.project_by_ingest_key(&key).unwrap(), Some(id));
        assert_eq!(s.project_by_ingest_key("chave-errada").unwrap(), None);
        // stored as bookkeeping, and filtered out of the app's env file and UI
        assert!(s.env_vars(id).unwrap().iter().any(|v| v.key.starts_with("__WEBO_")));
    }

    #[test]
    fn logs_are_searchable_resumable_and_pruned() {
        let s = store();
        s.upsert_discovered("app", "app", None, None, 1).unwrap();
        let id = s.project_by_slug("app").unwrap().unwrap().id;
        let line = |ts: i64, c: &str, text: &str| LogLine {
            ts,
            container: c.into(),
            stream: "stdout".into(),
            line: text.into(),
        };
        s.insert_logs(id, &[
            line(100, "app", "server started on port 3000"),
            line(200, "app", "GET /health 200"),
            line(300, "db", "database system is ready"),
            line(400, "app", "ERROR connection refused"),
        ]).unwrap();

        // newest first
        let all = s.search_logs(id, None, None, None, 10).unwrap();
        assert_eq!(all.len(), 4);
        assert_eq!(all[0].ts, 400);

        // full text
        let hits = s.search_logs(id, Some("connection"), None, None, 10).unwrap();
        assert_eq!(hits.len(), 1);
        assert!(hits[0].line.contains("ERROR"));

        // by container and by window
        let only_db = s.search_logs(id, None, Some("db"), None, 10).unwrap();
        assert_eq!(only_db.len(), 1);
        let recent = s.search_logs(id, None, None, Some(250), 10).unwrap();
        assert_eq!(recent.len(), 2, "only lines at or after the window");

        // collection resumes from the newest stored line
        assert_eq!(s.last_log_ts(id, "app").unwrap(), Some(400));
        assert_eq!(s.last_log_ts(id, "nope").unwrap(), None);

        // pruning drops the oldest and keeps the newest
        let bytes = s.logs_bytes(id).unwrap();
        assert!(bytes > 0);
        assert_eq!(s.prune_logs(id, bytes + 1000).unwrap(), 0, "under the cap nothing is dropped");
        assert!(s.prune_logs(id, 1).unwrap() > 0);
        let left = s.search_logs(id, None, None, None, 10).unwrap();
        assert!(left.iter().all(|l| l.ts >= 100));

        s.delete_logs(id).unwrap();
        assert!(s.search_logs(id, None, None, None, 10).unwrap().is_empty());
    }

    #[test]
    fn database_and_env_lifecycle() {
        let s = store();
        s.upsert_discovered("loja", "loja", None, None, 1).unwrap();
        let id = s.project_by_slug("loja").unwrap().unwrap().id;
        assert!(s.database(id).unwrap().is_none());

        let db = Database {
            kind: "postgres".into(),
            container: Some("loja-db".into()),
            db_name: Some("loja".into()),
            username: Some("loja".into()),
            password: Some("s3cr3t".into()),
            volume: None,
            file_path: None,
            persisted: true,
            created_at: 10,
        };
        s.set_database(id, &db).unwrap();
        let got = s.database(id).unwrap().unwrap();
        assert_eq!(got.kind, "postgres");
        assert_eq!(got.password.as_deref(), Some("s3cr3t"));

        // upsert without a password keeps the stored one
        let mut without = db.clone();
        without.password = None;
        without.db_name = Some("loja2".into());
        s.set_database(id, &without).unwrap();
        let got = s.database(id).unwrap().unwrap();
        assert_eq!(got.db_name.as_deref(), Some("loja2"));
        assert_eq!(got.password.as_deref(), Some("s3cr3t"), "password survives an upsert");

        // env vars: managed first, hand-made deletable
        s.set_env(id, "DATABASE_URL", "postgres://x", true).unwrap();
        s.set_env(id, "API_KEY", "abc", false).unwrap();
        let vars = s.env_vars(id).unwrap();
        assert_eq!(vars[0].key, "DATABASE_URL", "managed comes first");
        assert!(vars[0].managed);
        assert!(!s.delete_env(id, "DATABASE_URL").unwrap(), "managed cannot be deleted by hand");
        assert!(s.delete_env(id, "API_KEY").unwrap());
        assert_eq!(s.env_vars(id).unwrap().len(), 1);

        // the password never leaks through serde
        let json = serde_json::to_string(&got).unwrap();
        assert!(!json.contains("s3cr3t"), "password is never serialized");

        s.delete_database(id).unwrap();
        assert!(s.database(id).unwrap().is_none());
    }

    #[test]
    fn deleting_a_project_takes_database_and_envs() {
        let s = store();
        s.upsert_discovered("x", "x", None, None, 1).unwrap();
        let id = s.project_by_slug("x").unwrap().unwrap().id;
        s.set_database(id, &Database {
            kind: "sqlite".into(), container: None, db_name: None, username: None, password: None,
            volume: Some("x_data".into()), file_path: Some("/data/app.db".into()),
            persisted: true, created_at: 1,
        }).unwrap();
        s.set_env(id, "K", "v", false).unwrap();
        s.delete_project("x").unwrap();
        assert!(s.database(id).unwrap().is_none());
        assert!(s.env_vars(id).unwrap().is_empty());
    }

    #[test]
    fn auto_domain_is_reserved_once_and_routes_are_listed() {
        let s = store();
        s.upsert_discovered("loja", "loja", None, None, 1).unwrap();
        s.set_auto_domain_if_empty("loja", "cedar-mint-opal.example.com", 3000).unwrap();
        s.set_auto_domain_if_empty("loja", "outro-nome.example.com", 8080).unwrap();
        let p = s.project_by_slug("loja").unwrap().unwrap();
        assert_eq!(p.auto_domain.as_deref(), Some("cedar-mint-opal.example.com"), "never changes");
        assert_eq!(p.port, Some(3000));

        s.set_custom_domain("loja", Some("loja.cliente.com")).unwrap();
        let routes = s.routes().unwrap();
        assert_eq!(routes.len(), 2);
        assert!(routes.contains(&("cedar-mint-opal.example.com".into(), "http://loja:3000".into())));
        assert!(routes.contains(&("loja.cliente.com".into(), "http://loja:3000".into())));

        s.set_custom_domain("loja", None).unwrap();
        assert_eq!(s.routes().unwrap().len(), 1, "disconnected domain leaves the routes");
    }

    #[test]
    fn set_tech_fills_once_and_never_overwrites() {
        let s = store();
        s.upsert_discovered("codo", "codo", None, None, 1).unwrap();
        assert_eq!(s.project_by_slug("codo").unwrap().unwrap().tech, None);
        s.set_tech_if_empty("codo", "rust").unwrap();
        s.set_tech_if_empty("codo", "ruby").unwrap();
        assert_eq!(s.project_by_slug("codo").unwrap().unwrap().tech.as_deref(), Some("rust"));
    }

    #[test]
    fn delete_project_cascades_builds_and_versions() {
        let s = store();
        s.upsert_discovered("cafe", "cafe", None, None, 1).unwrap();
        let id = s.project_by_slug("cafe").unwrap().unwrap().id;
        s.replace_builds(id, &[Build {
            run_id: 1, workflow: "Deploy".into(), status: "completed".into(), conclusion: None,
            commit_sha: "x".into(), commit_msg: "m".into(), branch: "main".into(),
            duration_secs: 1, created_at: 1,
        }]).unwrap();
        assert!(s.delete_project("cafe").unwrap());
        assert!(s.project_by_slug("cafe").unwrap().is_none());
        assert!(s.builds(id, 10).unwrap().is_empty(), "builds gone with the project");
        assert!(!s.delete_project("cafe").unwrap(), "second delete is a no-op");
    }

    #[test]
    fn open_migrates_a_pre_workflow_database() {
        let dir = std::env::temp_dir().join(format!("webo-migrate-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("old.db");
        {
            // simulate a database created before the workflow column existed
            let conn = Connection::open(&path).unwrap();
            conn.execute_batch(
                "CREATE TABLE projects (id INTEGER PRIMARY KEY, server_id TEXT NOT NULL DEFAULT 'local',
                    slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, source TEXT NOT NULL,
                    compose_project TEXT, repo_owner TEXT, repo_name TEXT, domain TEXT, created_at INTEGER NOT NULL);
                 CREATE TABLE builds (id INTEGER PRIMARY KEY, project_id INTEGER NOT NULL,
                    run_id INTEGER NOT NULL, status TEXT NOT NULL, conclusion TEXT,
                    commit_sha TEXT NOT NULL, commit_msg TEXT NOT NULL, branch TEXT NOT NULL,
                    duration_secs INTEGER NOT NULL, created_at INTEGER NOT NULL,
                    UNIQUE (project_id, run_id));",
            ).unwrap();
        }
        let s = Store::open(&path).unwrap();
        s.upsert_discovered("codo", "codo", None, None, 1).unwrap();
        let id = s.project_by_slug("codo").unwrap().unwrap().id;
        s.replace_builds(id, &[Build {
            run_id: 1, workflow: "Deploy".into(), status: "completed".into(),
            conclusion: Some("success".into()), commit_sha: "x".into(), commit_msg: "m".into(),
            branch: "main".into(), duration_secs: 1, created_at: 1,
        }]).unwrap();
        assert_eq!(s.builds(id, 10).unwrap()[0].workflow, "Deploy");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn ignored_issues_stay_ignored_and_bulk_actions_work() {
        let s = store();
        s.upsert_discovered("app", "app", None, None, 1).unwrap();
        let id = s.project_by_slug("app").unwrap().unwrap().id;
        let i1 = s.record_error(id, "fp-1", "a", "server", "app", "a", 10, None).unwrap();
        let i2 = s.record_error(id, "fp-2", "b", "server", "app", "b", 20, None).unwrap();
        let i3 = s.record_error(id, "fp-3", "c", "browser", "u", "c", 30, None).unwrap();

        // ignoring silences even new occurrences
        assert_eq!(s.set_issue_state(id, &[i1], "ignored").unwrap(), 1);
        s.record_error(id, "fp-1", "a", "server", "app", "a de novo", 40, None).unwrap();
        let ign = s.issues(id, Some("ignored")).unwrap();
        assert_eq!(ign.len(), 1);
        assert_eq!(ign[0].count, 2, "occurrences still counted while ignored");
        assert_eq!(s.open_issue_count(id).unwrap(), 2, "ignored is not open");

        // bulk resolve + counts
        assert_eq!(s.set_issue_state(id, &[i2, i3], "resolved").unwrap(), 2);
        assert_eq!(s.issue_counts(id).unwrap(), (0, 2, 1));
        // invalid state and empty list are no-ops
        assert_eq!(s.set_issue_state(id, &[i2], "weird").unwrap(), 0);
        assert_eq!(s.set_issue_state(id, &[], "open").unwrap(), 0);

        // delete takes the events along
        assert_eq!(s.delete_issues(id, &[i1, 9999]).unwrap(), 1);
        assert!(s.event_timestamps(i1, 10).unwrap().is_empty());
        assert_eq!(s.issues(id, None).unwrap().len(), 2);
    }

    #[test]
    fn saved_queries_upsert_order_and_die_with_the_project() {
        let s = store();
        s.upsert_discovered("loja", "loja", None, None, 1).unwrap();
        let id = s.project_by_slug("loja").unwrap().unwrap().id;

        s.save_query(id, "leads por estado", "select 1", 100).unwrap();
        s.save_query(id, "pedidos", "select 2", 200).unwrap();
        // upsert replaces the sql
        s.save_query(id, "leads por estado", "select 1, 2", 300).unwrap();
        let qs = s.saved_queries(id).unwrap();
        assert_eq!(qs.len(), 2);
        assert_eq!(qs[0].name, "leads por estado", "most recently touched first");
        assert_eq!(qs[0].sql, "select 1, 2");

        // running one bumps it to the top
        s.mark_query_run(id, "pedidos", 400).unwrap();
        assert_eq!(s.saved_queries(id).unwrap()[0].name, "pedidos");
        assert_eq!(s.saved_queries(id).unwrap()[0].last_run_at, Some(400));

        assert!(s.delete_query(id, "pedidos").unwrap());
        assert!(!s.delete_query(id, "pedidos").unwrap(), "second delete is a no-op");

        s.delete_project("loja").unwrap();
        assert!(s.saved_queries(id).unwrap().is_empty(), "cascade");
    }

    #[test]
    fn samples_persist_upsert_and_prune() {
        let s = store();
        let mk = |ts| StoredSample { ts, cpu_pct: 1.5, mem_bytes: 100, disk_bps: 10, net_rx_bps: 5, net_tx_bps: 3 };
        s.insert_sample("server", &mk(100)).unwrap();
        s.insert_sample("server", &mk(400)).unwrap();
        s.insert_sample("project:app", &mk(100)).unwrap();
        // same (scope, ts) updates in place
        s.insert_sample("server", &StoredSample { cpu_pct: 9.0, ..mk(400) }).unwrap();

        let got = s.samples("server", 0).unwrap();
        assert_eq!(got.len(), 2, "scopes are isolated");
        assert_eq!(got[0].ts, 100, "oldest first");
        assert_eq!(got[1].cpu_pct, 9.0, "upsert replaced the point");

        let recent = s.samples("server", 200).unwrap();
        assert_eq!(recent.len(), 1);

        assert_eq!(s.prune_samples(200).unwrap(), 2, "old points of every scope go");
        assert_eq!(s.samples("project:app", 0).unwrap().len(), 0);
        assert_eq!(s.samples("server", 0).unwrap().len(), 1);
    }

    #[test]
    fn migration_maps_old_resolved_flag_to_state() {
        let dir = std::env::temp_dir().join(format!("webo-issue-migrate-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("old.db");
        {
            let conn = Connection::open(&path).unwrap();
            conn.execute_batch(
                "CREATE TABLE projects (id INTEGER PRIMARY KEY, server_id TEXT NOT NULL DEFAULT 'local',
                    slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, source TEXT NOT NULL,
                    compose_project TEXT, repo_owner TEXT, repo_name TEXT, domain TEXT, created_at INTEGER NOT NULL);
                 CREATE TABLE issues (id INTEGER PRIMARY KEY, project_id INTEGER NOT NULL,
                    fingerprint TEXT NOT NULL, title TEXT NOT NULL, source TEXT NOT NULL,
                    first_seen INTEGER NOT NULL, last_seen INTEGER NOT NULL,
                    count INTEGER NOT NULL DEFAULT 0, resolved INTEGER NOT NULL DEFAULT 0,
                    UNIQUE (project_id, fingerprint));
                 INSERT INTO projects (id, slug, name, source, created_at) VALUES (7, 'app', 'app', 'discovered', 1);
                 INSERT INTO issues (project_id, fingerprint, title, source, first_seen, last_seen, count, resolved)
                    VALUES (7, 'f1', 'old resolved', 'server', 1, 2, 3, 1),
                           (7, 'f2', 'old open', 'server', 1, 2, 1, 0);",
            ).unwrap();
        }
        let s = Store::open(&path).unwrap();
        assert_eq!(s.issues(7, Some("resolved")).unwrap().len(), 1);
        assert_eq!(s.issues(7, Some("open")).unwrap().len(), 1);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn open_on_disk_persists_across_reopen() {
        let dir = std::env::temp_dir().join(format!("webo-store-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("webo.db");
        {
            let s = Store::open(&path).unwrap();
            s.upsert_discovered("codo", "codo", None, None, 1).unwrap();
        }
        let s = Store::open(&path).unwrap();
        assert!(s.project_by_slug("codo").unwrap().is_some());
        std::fs::remove_dir_all(&dir).ok();
    }
}
